#!/usr/bin/env bash
# installing nginx on web-01 server per given requirements
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" | sudo tee /var/www/html/index.html
sudo service nginx start
