#!/usr/bin/env bash
# install and configure HAProxy load balancer on proper server

# install HAProxy
sudo apt update
sudo apt install -y haproxy
# configure HAPRoxy
# Set ENABLED to 1 if you want the init script to start haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
# define front end configuration
fefig="frontend www\n\tbind *:80\n\tdefault_backend nginx_pool\n"
echo -e "$fefig" | sudo tee -a /etc/haproxy/haproxy.cfg
# configure back end section
befig1="backend nginx_pool\n\tbalance roundrobin\n\tserver web-01 34.228.81.157:80 check"
befig2="server web-02 34.204.10.91:80 check"
echo -e "$befig1\t$befig2" | sudo tee -a /etc/haproxy/haproxy.cfg
# restart service
sudo servce haproxy restart
